server:
  port: 7005

fabric:
  config:
    env: local
    username: admin
    orgName: org1
    mspId: Org1MSP
    keyFile: private_key  #/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore
    certFile: admin_cert.pem    #/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts
    peer:
      - name: peer0.org1.example.com
        useTLS: true
        addr: 192.168.43.212:7051
        tlsPath: /Users/tanghu/fabric-samples/first-network/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
      - name: peer0.org2.example.com
        useTLS: true
        addr: 192.168.43.212:9051
        tlsPath: /Users/tanghu/fabric-samples/first-network/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/tls/server.crt
    order:
      - name: orderer.example.com
        addr: 192.168.43.212:7050
        useTLS: true
        tlsPath: /Users/tanghu/fabric-samples/first-network/crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/ca.crt
