server:
  port: 7002

spring:
  application:
    name: config-server  # 应用名称
  profiles:
    active: jdbc

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://120.78.121.110:7001/eureka/
  instance:
    preferIpAddress: true