server:
  port: 7003

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    preferIpAddress: true

user:
  username: zhangsan-local
  password: mima123456-local
  nickname: zs-local
